FOLDER: './experiments' # Experiment files saving path

TEST:
  FOLDER: './results' # Testing files saving path

DATASET:
  SMPL_PATH: 'deps/smpl'
  TRANSFORM_PATH: 'deps/transforms/'
  WORD_VERTILIZER_PATH: 'deps/glove/'
  HUMANML3D:
    ROOT: '/data/zss/Virtual_patient/text2motion/HumanML3D/HumanML3D' # HumanML3D directory
    SPLIT_ROOT: '/data/zss/Virtual_patient/text2motion/HumanML3D/HumanML3D' # HumanML3D splits directory


model:
  clip_path: 'deps/clip-vit-large-patch14' # bert model path for all text encoders
  # motion_clip_path: 'deps/motionclip'
  t2m_path: 'deps/t2m/'


